### ISSUE TITLE
Illegal value type for Enum

### ISSUE THREAD

**Issue by fjr619** [skydoves/Bundler#5]
**Please complete the following information:**
- Library Version 1.0.3
 
**Describe the Bug:**
Cant  get bundle for Enum
Example : 
ENUM
```
enum class FragmentIndex {
    NONE,
    SIMPLE_REQUEST
}
```
Activity 1
```
                intentOf<RequestActivity> {
                    +(Extras.FRAGMENT_INDEX to FragmentIndex.SIMPLE_REQUEST)
                    startActivity(this@MainActivity)
                }
```
Activity 2
```
private val index: FragmentIndex by  bundle(Extras.FRAGMENT_INDEX, FragmentIndex.NONE)
```
it will crash `Illegal value type.....`

**Expected Behavior:**

usually it will use getSerializableExtra({key})

**Comment by skydoves** [comment]
Hi, try the below code.

```kotlin
private val position: FragmentIndex? by bundle(Extras.FRAGMENT_INDEX) {  FragmentIndex.NONE }
```

For getting a reference type (non-primitive type) we should make it a nullable type via bundle function, and we can initialize the default value in the lambda.
